// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: '1:123456789000:web:0123456789abcdef',
    messagingSenderId: '123456789000',
    projectId: 'instagram-clone-placeholder',
    authDomain: 'instagram-clone-placeholder.firebaseapp.com',
    storageBucket: 'instagram-clone-placeholder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDbjYLbL34qGXAQUIRqUCJjeQK1ky3JGCg",
    appId: '1:256280889890:android:d6611fdec936a62050987b',
    messagingSenderId: '256280889890',
    databaseURL: 'https://insta-ghost-v2-default-rtdb.firebaseio.com/',
    projectId: 'insta-ghost-v2',
    storageBucket: 'insta-ghost-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: '1:123456789000:ios:0123456789abcdef',
    messagingSenderId: '123456789000',
    projectId: 'instagram-clone-placeholder',
    storageBucket: 'instagram-clone-placeholder.appspot.com',
    iosClientId: '123456789000-placeholder.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: '1:123456789000:ios:0123456789abcdef',
    messagingSenderId: '123456789000',
    projectId: 'instagram-clone-placeholder',
    storageBucket: 'instagram-clone-placeholder.appspot.com',
    iosClientId: '123456789000-placeholder.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
